version: "3.7"

services:
  vscode:
    build: .
    volumes:
      - ../:/workspace
      # Docker
      - ~/.docker:/home/vscode/.docker:z
      # Docker socket to access Docker server
      - /var/run/docker.sock:/var/run/docker.sock
      # SSH directory for Linux, OSX and WSL
      - ~/.ssh:/home/vscode/.ssh:z
      # For Windows without WSL, a copy will be made
      # from /tmp/.ssh to ~/.ssh to fix permissions
      # - ~/.ssh:/tmp/.ssh:ro
      # Shell history persistence
      - ~/.zsh_history:/home/vscode/.zsh_history:z
      # Git config
      - ~/.gitconfig:/home/vscode/.gitconfig:z
      # Kubernetes
      - ~/.kube:/home/vscode/.kube:z
    environment:
      - TZ=
    cap_add:
      # For debugging with dlv
      - SYS_PTRACE
    security_opt:
      # For debugging with dlv
      - seccomp:unconfined
    entrypoint: [ "zsh", "-c", "while sleep 1000; do :; done" ]
  database:
    image: postgres
    restart: always
    env_file: ../.env
